name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
        
      - name: Check out Actions repository
        uses: actions/checkout@master
        with:
          repository: deepanshu102021/github-actions
          token: ${{ secrets.GIT_TOKEN }}
          path: .github/actions/

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Containerize application and push to registry
        uses: ./.github/actions/containerization/
      
      - name: Deployment
        uses: ./.github/actions/deploy
