name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
        
      - name: Check out Actions repository
        uses: actions/checkout@master
        with:
          repository: deepanshu102021/github-actions
          token: ${{ secrets.GIT_TOKEN }}

      - name: Setup GCP Service Account
        uses: ./prepare-environment.yaml

      - name: Containerize application and push to registry
        uses: ./containerisation.yaml
      
      - name: Deployment
        uses: ./deploy.yaml
